"""FastAPI demo backend — generated by Vesper"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional

app = FastAPI(
    title="Vesper Demo API",
    description="Starter FastAPI backend — extend me with Vesper AI",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── In-memory data store (replace with a real DB) ────────────────────────────
_items: list[dict] = [
    {"id": 1, "name": "First item",  "done": False},
    {"id": 2, "name": "Second item", "done": True},
]
_next_id = 3


class ItemCreate(BaseModel):
    name: str
    done: bool = False


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {"message": "Hello from Vesper!", "status": "ok", "version": "0.1.0"}


@app.get("/health")
def health_check():
    return {"status": "healthy"}


@app.get("/items")
def list_items():
    return _items


@app.get("/items/{item_id}")
def get_item(item_id: int):
    item = next((i for i in _items if i["id"] == item_id), None)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item


@app.post("/items", status_code=201)
def create_item(body: ItemCreate):
    global _next_id
    item = {"id": _next_id, **body.model_dump()}
    _items.append(item)
    _next_id += 1
    return item


@app.delete("/items/{item_id}", status_code=204)
def delete_item(item_id: int):
    global _items
    _items = [i for i in _items if i["id"] != item_id]


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
