/**
 * Demo project files seeded on first visit or on demand.
 * Represents a minimal React + FastAPI full-stack starter.
 */

export interface DemoFile {
  path: string;
  content: string;
}

export const DEMO_PROJECT_FILES: DemoFile[] = [
  {
    path: "README.md",
    content: `# Demo Project — React + FastAPI

A minimal full-stack starter scaffolded by **Vesper**.
Ask the AI agent to extend, refactor, or deploy it.

## Structure
\`\`\`
├── frontend/
│   ├── App.jsx        — React component
│   └── index.html     — HTML entry point
├── api/
│   └── main.py        — FastAPI backend
└── requirements.txt   — Python dependencies
\`\`\`

## Running the backend
\`\`\`bash
pip install -r requirements.txt
uvicorn api.main:app --reload --port 8000
\`\`\`

## Running the frontend
Open \`frontend/index.html\` in a browser, or serve with any static server.

---
*Generated by Vesper · Full-stack AI IDE by Skinopro Tech Solutions*
`,
  },
  {
    path: "frontend/App.jsx",
    content: `import { useState, useEffect } from "react";

const API_BASE = "http://localhost:8000";

export default function App() {
  const [count, setCount]       = useState(0);
  const [greeting, setGreeting] = useState("Connecting to API…");
  const [items, setItems]       = useState([]);

  useEffect(() => {
    fetch(\`\${API_BASE}/\`)
      .then(r => r.json())
      .then(d => setGreeting(d.message))
      .catch(() => setGreeting("API offline — start the backend first"));

    fetch(\`\${API_BASE}/items\`)
      .then(r => r.json())
      .then(setItems)
      .catch(() => {});
  }, []);

  return (
    <div style={{ fontFamily: "system-ui, sans-serif", maxWidth: 640, margin: "60px auto", padding: "0 24px" }}>
      <header style={{ borderBottom: "1px solid #e5e7eb", paddingBottom: 24, marginBottom: 32 }}>
        <h1 style={{ color: "#7c3aed", margin: 0 }}>🚀 Vesper Demo</h1>
        <p style={{ color: "#6b7280", margin: "4px 0 0" }}>Full-stack AI IDE Starter</p>
      </header>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 14, color: "#374151", marginBottom: 8 }}>API Status</h2>
        <code style={{ background: "#f3f4f6", padding: "8px 14px", borderRadius: 8, display: "block", fontSize: 13 }}>
          {greeting}
        </code>
      </section>

      <section style={{ marginBottom: 32 }}>
        <h2 style={{ fontSize: 14, color: "#374151", marginBottom: 8 }}>Interactive Counter</h2>
        <div style={{ display: "flex", alignItems: "center", gap: 16 }}>
          <button
            onClick={() => setCount(c => c + 1)}
            style={{
              background: "#7c3aed", color: "#fff", border: "none",
              borderRadius: 8, padding: "10px 24px", cursor: "pointer", fontSize: 15,
            }}
          >
            + Increment
          </button>
          <span style={{ fontSize: 20, fontWeight: 700, color: "#7c3aed" }}>{count}</span>
          <button
            onClick={() => setCount(0)}
            style={{
              background: "transparent", color: "#9ca3af", border: "1px solid #e5e7eb",
              borderRadius: 8, padding: "10px 16px", cursor: "pointer", fontSize: 13,
            }}
          >
            Reset
          </button>
        </div>
      </section>

      {items.length > 0 && (
        <section>
          <h2 style={{ fontSize: 14, color: "#374151", marginBottom: 8 }}>Items from API</h2>
          <ul style={{ listStyle: "none", padding: 0, margin: 0 }}>
            {items.map(item => (
              <li key={item.id} style={{ padding: "8px 0", borderBottom: "1px solid #f3f4f6", fontSize: 13, color: "#4b5563" }}>
                <strong>#{item.id}</strong> — {item.name}
              </li>
            ))}
          </ul>
        </section>
      )}
    </div>
  );
}
`,
  },
  {
    path: "frontend/index.html",
    content: `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Vesper Demo</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module">
      import { createElement, useState, useEffect } from "https://esm.sh/react@18";
      import { createRoot } from "https://esm.sh/react-dom@18/client";

      /* Inline App for zero-build preview */
      function App() {
        const [count, setCount] = useState(0);
        return createElement("div", {
          style: { fontFamily: "system-ui", maxWidth: 500, margin: "60px auto", padding: "0 20px" }
        },
          createElement("h1", { style: { color: "#7c3aed" } }, "🚀 Vesper Demo"),
          createElement("p", null, "Edit App.jsx and rebuild, or serve with Vite."),
          createElement("button", {
            onClick: () => setCount(c => c + 1),
            style: { background: "#7c3aed", color: "#fff", border: "none", borderRadius: 8, padding: "10px 20px", cursor: "pointer" }
          }, \`Clicked \${count} time\${count !== 1 ? "s" : ""}\`)
        );
      }

      createRoot(document.getElementById("root")).render(createElement(App));
    </script>
  </body>
</html>
`,
  },
  {
    path: "api/main.py",
    content: `"""FastAPI demo backend — generated by Vesper"""
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import Optional

app = FastAPI(
    title="Vesper Demo API",
    description="Starter FastAPI backend — extend me with Vesper AI",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── In-memory data store (replace with a real DB) ────────────────────────────
_items: list[dict] = [
    {"id": 1, "name": "First item",  "done": False},
    {"id": 2, "name": "Second item", "done": True},
]
_next_id = 3


class ItemCreate(BaseModel):
    name: str
    done: bool = False


# ── Routes ───────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    return {"message": "Hello from Vesper!", "status": "ok", "version": "0.1.0"}


@app.get("/health")
def health_check():
    return {"status": "healthy"}


@app.get("/items")
def list_items():
    return _items


@app.get("/items/{item_id}")
def get_item(item_id: int):
    item = next((i for i in _items if i["id"] == item_id), None)
    if not item:
        raise HTTPException(status_code=404, detail="Item not found")
    return item


@app.post("/items", status_code=201)
def create_item(body: ItemCreate):
    global _next_id
    item = {"id": _next_id, **body.model_dump()}
    _items.append(item)
    _next_id += 1
    return item


@app.delete("/items/{item_id}", status_code=204)
def delete_item(item_id: int):
    global _items
    _items = [i for i in _items if i["id"] != item_id]


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, reload=True)
`,
  },
  {
    path: "requirements.txt",
    content: `fastapi>=0.104.0
uvicorn[standard]>=0.24.0
pydantic>=2.0.0
httpx>=0.25.0
`,
  },
];

/** localStorage key — set after demo is seeded to avoid re-seeding */
export const DEMO_SEEDED_KEY = "vesper.demo.seeded";
